name: App
states:
  - name: deviceToken
    type: Data?
  - name: keychainCredentials
    type: Fundamentals.Credentials?
actions:
  - name: appDidFinishLaunching
  - name: didRegisterForRemoteNotifications
    subtypes:
      - type: Result<Data, NSError>
        name: result
  - name: didLoadCredentials
    subtypes:
      - type: Result<Fundamentals.Credentials, NSError>
        name: result
  - name: loadCourses
  - name: didLoadCourses
    subtypes:
      - type: Result<[CourseState], NSError>
        name: result
dependencies:
  - courses.yaml
  - user.yaml
